server:
  port: 8000

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: multicast://224.5.6.7:1234
#    address: N/A
  protocol:
    name: dubbo
    port: 20880