version: '3.1'

services:
  redis:
    image: library/redis:latest
    container_name: lottery-redis
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass Re.Lottery!!2022
    volumes:
      - ../redis/data:/data #挂载 Redis数据
      - ../redis/conf/redis.conf:/usr/local/etc/redis/redis.conf #挂载 Redis配置
    ports:
      - "6379:6379"
    restart: always
