server:
  port: 8080

spring:
  datasource:
    username: root
    password: MYSQL.RPA@2020
    url: jdbc:mysql://172.22.1.159:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: kit.pano.lottery.rpc